#!/usr/bin/env python3

# import the libraries
import re
import csv

# create the dictionaries
error_counts = {}
per_user = {}

with open("syslog.log") as f:
    for line in f.readlines():
        info_match = re.search(r'.* INFO .* \((\w*)\)', line)
        error_match = re.search(r'.* ERROR (.*) \((\w*)\)', line)

        if info_match:
            username = info_match.group(1)
            per_user.setdefault(username, {"INFO": 0, "ERROR": 0})
            per_user[username]["INFO"] += 1
       
        elif error_match:
            username = error_match.group(2)
            message = error_match.group(1).strip()
            per_user.setdefault(username, {"INFO": 0, "ERROR": 0})
            per_user[username]["ERROR"] += 1
            error_counts[message] = error_counts.get(message, 0) + 1
f.close()

sorted_errors = sorted(error_counts.items(), key=lambda x: x[1], reverse=True)
sorted_errors.insert(0, ("Error", "Count"))

sorted_users = sorted(per_user.items())
#List comprehension, basically seperating [(key, {X: value1, Y: value2})] into [(key, value1, value2)]
sorted_users = [(u, c["INFO"], c["ERROR"]) for u, c in sorted_users]
sorted_users.insert(0, ("Username", "INFO", "ERROR"))

with open("error_message.csv", "w", newline="") as e:
    csv.writer(e).writerows(sorted_errors)

with open("user_statistics.csv", "w", newline="") as u:
    csv.writer(u).writerows(sorted_users)
